name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Указываем конкретную версию, как у вас локально
          cache: 'pip'  # Кэшируем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/ -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build binary
        run: |
          pyinstaller --onefile src/remove_background.py
      - name: Test binary (optional)
        run: |
          ./dist/remove_background --help  # Проверка, что бинарник запускается
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-gif-void-binary-linux
          path: dist/remove_background
          retention-days: 30  # Храним артефакт 30 дней